"""removed outstanding column

Revision ID: 2629f66acc0e
Revises: 86832d78845e
Create Date: 2025-06-22 21:33:25.900433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2629f66acc0e'
down_revision = '86832d78845e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('outstanding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outstanding', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
