"""Modify credit card columns to for better tracking

Revision ID: 34aa021e0d86
Revises: b9d66c58c309
Create Date: 2025-06-21 17:53:21.206452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34aa021e0d86'
down_revision = 'b9d66c58c309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_cycle_start', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('outstanding', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('last_payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_payment_amount', sa.Float(), nullable=True))
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=False))
        batch_op.drop_column('last_payment_amount')
        batch_op.drop_column('last_payment_date')
        batch_op.drop_column('outstanding')
        batch_op.drop_column('billing_cycle_start')

    # ### end Alembic commands ###
