"""Add is_billed column to CreditCardTransaction

Revision ID: 63dad57d3337
Revises: 2629f66acc0e
Create Date: 2025-06-25 22:04:16.363154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63dad57d3337'
down_revision = '2629f66acc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_billed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('is_billed')

    # ### end Alembic commands ###
