"""add billed_unpaid, unbilled_spends, total_payable columns

Revision ID: 86832d78845e
Revises: 34aa021e0d86
Create Date: 2025-06-22 19:39:40.588827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86832d78845e'
down_revision = '34aa021e0d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billed_unpaid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unbilled_spends', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('unbilled_spends')
        batch_op.drop_column('billed_unpaid')

    # ### end Alembic commands ###
