"""Add platform and category columns to Asset, remove bank_id

Revision ID: b9d66c58c309
Revises: c5ad959ee78b
Create Date: 2025-06-21 11:50:06.862616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d66c58c309'
down_revision = 'c5ad959ee78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('fk_asset_bank_id', type_='foreignkey')
        batch_op.drop_column('bank_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_asset_bank_id', 'bank', ['bank_id'], ['id'])
        batch_op.drop_column('category')
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
