"""new financial transaction models

Revision ID: c5ad959ee78b
Revises: d23a6b957ee1
Create Date: 2025-03-25 10:58:55.789001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ad959ee78b'
down_revision = 'd23a6b957ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_transaction')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('bank_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bank', schema=None) as batch_op:
        batch_op.drop_column('transactions')

    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('transactions')

    with op.batch_alter_table('saving', schema=None) as batch_op:
        batch_op.alter_column('bank_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('transactions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transactions', sa.TEXT(), nullable=True))
        batch_op.alter_column('bank_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transactions', sa.TEXT(), nullable=True))

    with op.batch_alter_table('bank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transactions', sa.TEXT(), nullable=True))

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('bank_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('asset_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('asset_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('balance_after', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
