"""Add Asset and Transaction models

Revision ID: d23a6b957ee1
Revises: f865bb63842d
Create Date: 2025-01-26 22:32:38.046971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23a6b957ee1'
down_revision = 'f865bb63842d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('transactions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transactions', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
