"""Updated database models

Revision ID: f865bb63842d
Revises: 
Create Date: 2025-01-26 13:09:58.351602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f865bb63842d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bank_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('transactions', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_asset_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_asset_bank_id', 'bank', ['bank_id'], ['id'])
        batch_op.drop_column('asset_name')
        batch_op.drop_column('value')
        batch_op.drop_column('investment_type')

    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('used', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('transactions', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_credit_card_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('used_amount')
        batch_op.drop_column('card_name')

    with op.batch_alter_table('saving', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('bank_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('transactions', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_saving_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_saving_bank_id', 'bank', ['bank_id'], ['id'])
        batch_op.drop_column('total')
        batch_op.drop_column('category')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('total', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint('fk_saving_bank_id', type_='foreignkey')
        batch_op.drop_constraint('fk_saving_user_id', type_='foreignkey')
        batch_op.drop_column('transactions')
        batch_op.drop_column('balance')
        batch_op.drop_column('user_id')
        batch_op.drop_column('bank_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('used_amount', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint('fk_credit_card_user_id', type_='foreignkey')
        batch_op.drop_column('transactions')
        batch_op.drop_column('balance')
        batch_op.drop_column('used')
        batch_op.drop_column('user_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_type', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('value', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('asset_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_asset_bank_id', type_='foreignkey')
        batch_op.drop_constraint('fk_asset_user_id', type_='foreignkey')
        batch_op.drop_column('transactions')
        batch_op.drop_column('balance')
        batch_op.drop_column('bank_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
